---
name: Wait 30 seconds to simulate gate tests
"on":
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  after-approval:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: |
          date
          sleep 30s
          date

